/**
 * ############## SSP DATABASE DEFINITION ###############
 * # Author: Felipe F. de Souza Carvalho                #
 * # Date: 2015/02/15                                   #
 * # Script Version: 1.0                                #
 * # Target: MySQL 5.5.28                               #
 * ######################################################
 */

CREATE DATABASE SSP_DB CHARACTER SET latin1 COLLATE latin1_general_ci;

USE SSP_DB;

SET GLOBAL max_allowed_packet = 1024 * 1024 * 100;

CREATE TABLE ALLOWED_FILE_EXTENSION
(
	AFE_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	EXTENSION varchar(6)  NOT NULL ,
	GLOBAL_CONFIG_ID BIGINT  NOT NULL 
);


CREATE TABLE ANALYST
(
	ANALYST_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	MANAGER_ID  BIGINT  NULL ,
	EMPLOYEE_ID  varchar(20)  NULL ,
	FIRST_NAME  varchar(30)  NOT NULL ,
	LAST_NAME varchar(60)  NOT NULL ,
	CREATE_DATE  datetime  NOT NULL ,
	EMAIL varchar(60)  NOT NULL ,
	CONTACT_NUMBER varchar(20)  NULL ,
	ANALYST_STATUS  varchar(20)  NOT NULL ,
	GROUP_ID  BIGINT  NOT NULL,
	USERNAME  varchar(40)  NOT NULL
);


CREATE TABLE ATTACHMENT
(
	ATTACHMENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	FILENAME varchar(255)  NOT NULL ,
	SIZE numeric(10,2)  NULL ,
	STREAM  LONGBLOB NULL,
	TICKET_ID  BIGINT  NULL ,
	TICKET_STEP_ID  BIGINT  NULL
);


CREATE TABLE CATEGORY
(
	CATEGORY_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	NAME varchar(30)  NOT NULL ,
	DESCRIPTION varchar(255)  NOT NULL ,
	STATUS varchar(20)  NOT NULL,
	PRODUCT_ID BIGINT  NOT NULL
);


CREATE TABLE CREDENTIAL
(
	USERNAME  varchar(40)  NOT NULL ,
	PASSWORD  varchar(255)  NULL ,
	EXPIRATION_DATE datetime  NOT NULL ,
	STATUS varchar(30)  NOT NULL ,
	ACCESS_TYPE varchar(30)  NOT NULL
);


CREATE TABLE FAQ
(
	FAQ_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	DESCRIPTION varchar(50)  NOT NULL ,
	FAQ_TEXT text  NOT NULL ,
	VERSION_DATE datetime  NOT NULL ,
	VERSION  integer  NOT NULL ,
	FAQ_CATEG_ID  BIGINT  NOT NULL ,
	PRODUCT_ID  BIGINT  NOT NULL ,
	ANALYST_ID  BIGINT  NOT NULL
);


CREATE TABLE FAQ_CATEGORY
(
	FAQ_CATEG_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	NAME varchar(30)  NOT NULL ,
	DESCRIPTION varchar(255)  NOT NULL ,
	STATUS varchar(10)  NOT NULL 
);


CREATE TABLE GLOBAL_CONFIGURATION
(
	GLOBAL_CONFIG_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	ADMIN_EMAIL  varchar(60)  NOT NULL ,
	AUTO_CLOSE_TICKETS  TINYINT(1) DEFAULT 0 NOT NULL ,
	AUTO_CLOSE_TICKETS_TIME  integer  NULL ,
	ALLOW_AUTO_SIGUP TINYINT(1) DEFAULT 1 NOT NULL ,
	AUTH_MODE varchar(30)  NOT NULL ,
	AUTH_MAX_TENTATIVES  integer  NULL ,
	ATTACH_MAX_SIZE  integer  NOT NULL ,
	COMPANY varchar(40)  NULL ,
	COMPANY_LOGO  varbinary(1024)  NULL ,
	SMTP_SERVER  varchar(20)  NULL ,
	SMTP_PORT  integer  NULL ,
	SMTP_USER  varchar(20)  NULL ,
	SMTP_PASSWORD  varchar(20)  NULL 
);


CREATE TABLE IP_FILTER
(
	FILTER_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	PATTERN varchar(20)  NOT NULL ,
	ALLOWED_DENIED  varchar(10)  NOT NULL ,
	GLOBAL_CONFIG_ID  BIGINT  NOT NULL 
);


CREATE TABLE LOG
(
	LOG_ENTRY_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	EVENT  varchar(20)  NOT NULL ,
	EVENT_TYPE  varchar(20)  NOT NULL ,
	DATE  datetime  NOT NULL ,
	USER  varchar(20)  NOT NULL 
);


CREATE TABLE PRIORITY
(
	PRIORITY_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	NAME  varchar(30)  NOT NULL 
);


CREATE TABLE PRODUCT
(
	PRODUCT_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	NAME varchar(30)  NOT NULL ,
	DESCRIPTION  varchar(255)  NULL ,
	PRODUCT_TYPE  varchar(10)  NOT NULL 
);


CREATE TABLE RATING
(
	RATING_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	COMMENT  varchar(30)  NULL ,
	RATE TINYINT  default 0 ,
	SUBMITTED_ON datetime  NULL
);


CREATE TABLE REQUESTER
(
	REQUESTER_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	FIRST_NAME  varchar(30)  NOT NULL ,
	LAST_NAME varchar(60)  NOT NULL ,
	EMAIL  varchar(60)  NOT NULL ,
	CONTACT_NUMBER  varchar(20)  NOT NULL ,
	REQUESTER_STATUS  varchar(10)  NOT NULL ,
	CREATE_DATE  datetime  NOT NULL ,
	NOTES varchar(255)  NULL,
	USERNAME  varchar(40)  NOT NULL
);


CREATE TABLE ROUTE
(
	ROUTE_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	PRODUCT_ID  BIGINT  NULL ,
	CATEGORY_ID  BIGINT  NULL ,
	GROUP_ID  BIGINT  NULL ,
	ANALYST_ID  BIGINT  NULL 
);


CREATE TABLE SLA_CONFIGURATION
(
	SLA_CONFIG_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	WARNING_TIME integer  NULL ,
	LIMIT_TIME  integer  NULL ,
	SHOULD_ALERT_RESPONSIBLE  TINYINT  NOT NULL ,
	SHOULD_ALERT_MANAGER  TINYINT  NOT NULL ,
	PRIORITY_ID  BIGINT  NOT NULL 
);


CREATE TABLE SUPPORT_GROUP
(
	GROUP_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	NAME varchar(40)  NOT NULL ,
	GROUP_STATUS  varchar(10)  NOT NULL ,
	MANAGMENT_GROUP TINYINT(1) DEFAULT 0 NOT NULL,
	RECEIVE_NOT_ROUTED TINYINT(1) DEFAULT 1 NOT NULL
);


CREATE TABLE TICKET
(
	TICKET_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	TITLE varchar(50)  NOT NULL ,
	DESCRIPTION text  NOT NULL ,
	OPEN_DATE datetime  NOT NULL ,
	CLOSE_DATE datetime  NULL ,
	CANCEL_REASON varchar(255)  NULL ,
	REQUESTER_ID  BIGINT  NOT NULL ,
	PRODUCT_ID  BIGINT  NOT NULL,
	CATEGORY_ID  BIGINT  NOT NULL ,
	TICKET_STATUS_ID BIGINT  NOT NULL ,
	PRIORITY_ID  BIGINT  NOT NULL,
	CLOSED_BY varchar(40) NULL
);


CREATE TABLE TICKET_STATUS
(
	TICKET_STATUS_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	NAME varchar(30)  NOT NULL
);


CREATE TABLE TICKET_STEP
(
	TICKET_STEP_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	DESCRIPTION  text  NOT NULL ,
	DATE datetime  NOT NULL ,
	INTERNAL TINYINT(1) DEFAULT 0 NOT NULL ,
	TICKET_ID  BIGINT  NOT NULL ,
	ANALYST_ID  BIGINT  NULL,
	REQUESTER_ID  BIGINT  NULL
);


CREATE TABLE TREATMENT
(
	TREATMENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	START_DATE datetime  NOT NULL ,
	END_DATE  datetime  NULL ,
	ACTIVE TINYINT(1) DEFAULT 0 NOT NULL,
	CLOSED TINYINT(1) DEFAULT 0 NOT NULL,
	SHOULD_REDIRECT TINYINT(1) DEFAULT 1 NOT NULL,
	RATING_ID BIGINT NULL ,
	TICKET_ID  BIGINT  NOT NULL ,
	GROUP_ID  BIGINT  NULL,
	ANALYST_ID  BIGINT  NULL
);


-- Primary Keys

ALTER TABLE CREDENTIAL
	ADD CONSTRAINT  XPKCREDENCIAL PRIMARY KEY  NONCLUSTERED (USERNAME  ASC);


-- Referential Integrity


ALTER TABLE ALLOWED_FILE_EXTENSION
	ADD CONSTRAINT  R_1 FOREIGN KEY (GLOBAL_CONFIG_ID) REFERENCES GLOBAL_CONFIGURATION(GLOBAL_CONFIG_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE ANALYST
	ADD CONSTRAINT  R_2 FOREIGN KEY (MANAGER_ID) REFERENCES ANALYST(ANALYST_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE ANALYST
	ADD CONSTRAINT  R_3 FOREIGN KEY (GROUP_ID) REFERENCES SUPPORT_GROUP(GROUP_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE ANALYST
	ADD CONSTRAINT  R_4 FOREIGN KEY (USERNAME) REFERENCES CREDENTIAL(USERNAME)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE ATTACHMENT
	ADD CONSTRAINT  R_5 FOREIGN KEY (TICKET_ID) REFERENCES TICKET(TICKET_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE ATTACHMENT
	ADD CONSTRAINT  R_6 FOREIGN KEY (TICKET_STEP_ID) REFERENCES TICKET_STEP(TICKET_STEP_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE CATEGORY
	ADD CONSTRAINT  R_7 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE FAQ
	ADD CONSTRAINT  R_8 FOREIGN KEY (FAQ_CATEG_ID) REFERENCES FAQ_CATEGORY(FAQ_CATEG_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE FAQ
	ADD CONSTRAINT  R_9 FOREIGN KEY (ANALYST_ID) REFERENCES ANALYST(ANALYST_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE FAQ
	ADD CONSTRAINT  R_10 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE IP_FILTER
	ADD CONSTRAINT  R_11 FOREIGN KEY (GLOBAL_CONFIG_ID) REFERENCES GLOBAL_CONFIGURATION(GLOBAL_CONFIG_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE REQUESTER
	ADD CONSTRAINT  R_12 FOREIGN KEY (USERNAME) REFERENCES CREDENTIAL(USERNAME)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE ROUTE
	ADD CONSTRAINT  R_13 FOREIGN KEY (GROUP_ID) REFERENCES SUPPORT_GROUP(GROUP_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE ROUTE
	ADD CONSTRAINT  R_14 FOREIGN KEY (ANALYST_ID) REFERENCES ANALYST(ANALYST_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE ROUTE
	ADD CONSTRAINT  R_15 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE ROUTE
	ADD CONSTRAINT  R_16 FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE SLA_CONFIGURATION
	ADD CONSTRAINT  R_17 FOREIGN KEY (PRIORITY_ID) REFERENCES PRIORITY(PRIORITY_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE TICKET
	ADD CONSTRAINT  R_18 FOREIGN KEY (CLOSED_BY) REFERENCES CREDENTIAL(USERNAME)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE TICKET
	ADD CONSTRAINT  R_19 FOREIGN KEY (REQUESTER_ID) REFERENCES REQUESTER(REQUESTER_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE TICKET
	ADD CONSTRAINT  R_20 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE TICKET
	ADD CONSTRAINT  R_21 FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE TICKET
	ADD CONSTRAINT  R_22 FOREIGN KEY (TICKET_STATUS_ID) REFERENCES TICKET_STATUS(TICKET_STATUS_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE TICKET
	ADD CONSTRAINT  R_23 FOREIGN KEY (PRIORITY_ID) REFERENCES PRIORITY(PRIORITY_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE TICKET_STEP
	ADD CONSTRAINT  R_24 FOREIGN KEY (TICKET_ID) REFERENCES TICKET(TICKET_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE TICKET_STEP
	ADD CONSTRAINT  R_25 FOREIGN KEY (ANALYST_ID) REFERENCES ANALYST(ANALYST_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE TICKET_STEP
	ADD CONSTRAINT  R_26 FOREIGN KEY (REQUESTER_ID) REFERENCES REQUESTER(REQUESTER_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE TREATMENT
	ADD CONSTRAINT  R_27 FOREIGN KEY (TICKET_ID) REFERENCES TICKET(TICKET_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE TREATMENT
	ADD CONSTRAINT  R_28 FOREIGN KEY (GROUP_ID) REFERENCES SUPPORT_GROUP(GROUP_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE TREATMENT
	ADD CONSTRAINT  R_29 FOREIGN KEY (ANALYST_ID) REFERENCES ANALYST(ANALYST_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

ALTER TABLE TREATMENT
	ADD CONSTRAINT  R_30 FOREIGN KEY (RATING_ID) REFERENCES RATING(RATING_ID)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;